parameters:
    photopage.items.ids:
        - mariage
        - reportage
        - portrait
        - sport
        - art
        - nature

services:
#    pma_content.example:
#        class: %pma_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
