parameters:
    items:
        photo:
            - item.photo.mariage
            - item.photo.reportage
            - item.photo.portrait
            - item.photo.sport
            - item.photo.art
            - item.photo.nature
        video:
            - item.video.mariage
            - item.video.evenement
            - item.video.entreprise
            - item.video.spectacle
services:
#    pma_content.example:
#        class: %pma_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
