parameters:
    items:
        photo:
            - mariage
            - reportage
            - portrait
            - sport
            - art
            - nature
        video:
            - mariage
            - evenement
            - entreprise
            - spectacle
        carousel:
            - slide1
            - slide2
            - slide3
services:
#    pma_content.example:
#        class: %pma_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
