parameters:
    photopage.services.ids:
        - 'mariage'
        - 'reportage'

services:
#    pma_content.example:
#        class: %pma_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
