parameters:
#    maid_layout.example.class: Maid\LayoutBundle\Example

services:
#    maid_layout.example:
#        class: %maid_layout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
